# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f551c489c1f0b6921fea0de70d68897cb740c3019e5e8ded3528105a4d3507a8dc880f3840f4e4c15b415db106fb6e3b6f86345bc261246466402329500cf39f

test:
  secret_key_base: caf9d1b757d51d75f03c45a0cf3b12376964b153e399f01a0f4d153bf31b1d95e03cb8377450c444c7fe8a4cc29882ecb81b8517a6ef4544843a90f515c4ba62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
